// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SchulDbGenerator.Model
{
    [Table("Klasse")]
    public partial class Klasse
    {
        public Klasse()
        {
            Schuelers = new HashSet<Schueler>();
            Stundens = new HashSet<Stunde>();
        }

        [Key]
        [Column("K_Nr")]
        [StringLength(6)]
        public string KNr { get; set; }
        [Column("K_Schuljahr")]
        public int KSchuljahr { get; set; }
        [Column("K_Bez")]
        [StringLength(15)]
        public string KBez { get; set; }
        [Column("K_Vorstand")]
        [StringLength(3)]
        public string KVorstand { get; set; }
        [Column("K_Klaspr")]
        public int? KKlaspr { get; set; }
        [Column("K_Klasprstv")]
        public int? KKlasprstv { get; set; }
        [Column("K_Abteilung")]
        [StringLength(3)]
        [Required]
        public string KAbteilung { get; set; }

        [Column("K_Stammraum")]
        [StringLength(8)]
        public string KStammraum { get; set; }

        [Column("K_Schulstufe")]
        public int? KSchulstufe { get; set; }

        [Column("K_Datumvon", TypeName = "datetime")]
        public DateTime? KDatumvon { get; set; }
        [Column("K_Datumbis", TypeName = "datetime")]
        public DateTime? KDatumbis { get; set; }
        [ForeignKey(nameof(KAbteilung))]
        [InverseProperty(nameof(Abteilung.Klassens))]
        public virtual Abteilung KAbteilungNavigation { get; set; }
        [ForeignKey(nameof(KKlaspr))]
        [InverseProperty(nameof(Schueler.KlassenKKlasprNavigations))]
        public virtual Schueler KKlasprNavigation { get; set; }
        [ForeignKey(nameof(KKlasprstv))]
        [InverseProperty(nameof(Schueler.KlassenKKlasprstvNavigations))]
        public virtual Schueler KKlasprstvNavigation { get; set; }
        [ForeignKey(nameof(KVorstand))]
        [InverseProperty(nameof(Lehrer.Klassens))]
        public virtual Lehrer KVorstandNavigation { get; set; }
        [ForeignKey(nameof(KSchuljahr))]
        [InverseProperty(nameof(Schuljahr.Klassens))]
        public virtual Schuljahr KSchuljahrNavigation { get; set; }
        [InverseProperty(nameof(Schueler.SKlasseNavigation))]
        public virtual ICollection<Schueler> Schuelers { get; set; }
        [InverseProperty(nameof(Stunde.StKlasseNavigation))]
        public virtual ICollection<Stunde> Stundens { get; set; }

        [ForeignKey(nameof(KStammraum))]
        [InverseProperty(nameof(Raum.Klassen))]
        public virtual Raum KStammraumNavigation { get; set; }
    }
}