// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SchulDb.Model
{
    [Table("Geschlecht")]
    public partial class Geschlecht
    {
        public Geschlecht()
        {
            Schuelers = new HashSet<Schueler>();
        }

        [Key]
        [Column("Ges_ID")]
        public int GesId { get; set; }
        [Required]
        [Column("Ges_Mw")]
        [StringLength(10)]
        public string GesMw { get; set; }
        [Column("Ges_Maennlichweiblich")]
        [StringLength(50)]
        public string GesMaennlichweiblich { get; set; }
        [Column("Ges_Schuelerschuelerin")]
        [StringLength(255)]
        public string GesSchuelerschuelerin { get; set; }
        [Column("Ges_Lehrerlehrerin")]
        [StringLength(255)]
        public string GesLehrerlehrerin { get; set; }

        [InverseProperty(nameof(Schueler.SGeschlechtNavigation))]
        public virtual ICollection<Schueler> Schuelers { get; set; }
    }
}