// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SchulDb.Model
{
    [Table("Pruefung")]
    public partial class Pruefung
    {
        [Key]
        [Column("P_DatumZeit")]
        public DateTime PDatumZeit { get; set; }
        [Key]
        [Column("P_Pruefer")]
        [StringLength(8)]
        public string PPruefer { get; set; }
        [Key]
        [Column("P_Gegenstand")]
        [StringLength(8)]
        public string PGegenstand { get; set; }
        [Column("P_Kandidat")]
        public int PKandidat { get; set; }
        [Column("P_Art")]
        [StringLength(1)]
        public string PArt { get; set; }
        [Column("P_Note")]
        public int? PNote { get; set; }

        [ForeignKey(nameof(PGegenstand))]
        [InverseProperty(nameof(Gegenstand.Pruefungens))]
        public virtual Gegenstand PGegenstandNavigation { get; set; }
        [ForeignKey(nameof(PKandidat))]
        [InverseProperty(nameof(Schueler.Pruefungens))]
        public virtual Schueler PKandidatNavigation { get; set; }
        [ForeignKey(nameof(PPruefer))]
        [InverseProperty(nameof(Lehrer.Pruefungens))]
        public virtual Lehrer PPrueferNavigation { get; set; }
    }
}