// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SchulDb.Model
{
    [Table("Schueler")]
    public partial class Schueler
    {
        public Schueler()
        {
            KlassenKKlasprNavigations = new HashSet<Klasse>();
            KlassenKKlasprstvNavigations = new HashSet<Klasse>();
            Pruefungens = new HashSet<Pruefung>();
        }

        [Key]
        [Column("S_Nr")]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]  // Für SQL Server, sonst glaubt EF Core es ist ein Autowert.
        public int SNr { get; set; }
        [Required]
        [Column("S_Klasse")]
        [StringLength(8)]
        public string SKlasse { get; set; }
        [Required]
        [Column("S_Zuname")]
        [StringLength(255)]
        public string SZuname { get; set; }
        [Required]
        [Column("S_Vorname")]
        [StringLength(255)]
        public string SVorname { get; set; }
        [Column("S_Geschlecht")]
        public int SGeschlecht { get; set; }
        [Column("S_Gebdatum")]
        public DateTime? SGebdatum { get; set; }
        [Column("S_Strasse")]
        [StringLength(255)]
        public string SStrasse { get; set; }
        [Column("S_Hausnummer")]
        [StringLength(255)]
        public string SHausnummer { get; set; }
        [Column("S_Postleitzahl")]
        public int? SPostleitzahl { get; set; }
        [Column("S_Ort")]
        [StringLength(255)]
        public string SOrt { get; set; }
        [Column("S_Staatsb")]
        [StringLength(8)]
        public string SStaatsb { get; set; }
        [Column("S_Religion")]
        public int? SReligion { get; set; }

        [ForeignKey(nameof(SGeschlecht))]
        [InverseProperty(nameof(Geschlecht.Schuelers))]
        public virtual Geschlecht SGeschlechtNavigation { get; set; }
        [ForeignKey(nameof(SKlasse))]
        [InverseProperty(nameof(Klasse.Schuelers))]
        public virtual Klasse SKlasseNavigation { get; set; }
        [ForeignKey(nameof(SReligion))]
        [InverseProperty(nameof(Religion.Schuelers))]
        public virtual Religion SReligionNavigation { get; set; }
        [ForeignKey(nameof(SStaatsb))]
        [InverseProperty(nameof(Staat.Schuelers))]
        public virtual Staat SStaatsbNavigation { get; set; }
        [InverseProperty(nameof(Klasse.KKlasprNavigation))]
        public virtual ICollection<Klasse> KlassenKKlasprNavigations { get; set; }
        [InverseProperty(nameof(Klasse.KKlasprstvNavigation))]
        public virtual ICollection<Klasse> KlassenKKlasprstvNavigations { get; set; }
        [InverseProperty(nameof(Pruefung.PKandidatNavigation))]
        public virtual ICollection<Pruefung> Pruefungens { get; set; }
    }
}