// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SchulDb.Model
{
    [Table("Staat")]
    public partial class Staat
    {
        public Staat()
        {
            Schuelers = new HashSet<Schueler>();
        }

        [Key]
        [Column("Sta_Nr")]
        [StringLength(8)]
        public string StaNr { get; set; }
        [Required]
        [Column("Sta_Name")]
        [StringLength(255)]
        public string StaName { get; set; }
        [Column("Sta_Staatsb")]
        [StringLength(255)]
        public string StaStaatsb { get; set; }
        [Column("Sta_Euland")]
        [StringLength(255)]
        public bool StaEuland { get; set; }

        [InverseProperty(nameof(Schueler.SStaatsbNavigation))]
        public virtual ICollection<Schueler> Schuelers { get; set; }
    }
}