// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SchulDb.Model
{
    [Table("Stunde")]
    public partial class Stunde
    {
        [Key]
        [Column("St_Stunde")]
        public int StStunde { get; set; }
        [Key]
        [Column("St_Tag")]
        public int StTag { get; set; }
        [Key]
        [Column("St_Lehrer")]
        [StringLength(8)]
        public string StLehrer { get; set; }
        [Key]
        [Required]
        [Column("St_Klasse")]
        [StringLength(8)]
        public string StKlasse { get; set; }
        [Required]
        [Column("St_Gegenstand")]
        [StringLength(8)]
        public string StGegenstand { get; set; }
        [Column("St_Raum")]
        [StringLength(8)]
        public string StRaum { get; set; }

        [ForeignKey(nameof(StStunde))]
        [InverseProperty(nameof(Stundenraster.Stundens))]
        public virtual Stundenraster StStundeNavigation { get; set; }
        [ForeignKey(nameof(StGegenstand))]
        [InverseProperty(nameof(Gegenstand.Stundens))]
        public virtual Gegenstand StGegenstandNavigation { get; set; }
        [ForeignKey(nameof(StKlasse))]
        [InverseProperty(nameof(Klasse.Stundens))]
        public virtual Klasse StKlasseNavigation { get; set; }
        [ForeignKey(nameof(StLehrer))]
        [InverseProperty(nameof(Lehrer.Stundens))]
        public virtual Lehrer StLehrerNavigation { get; set; }
        [ForeignKey(nameof(StRaum))]
        [InverseProperty(nameof(Raum.Stundens))]
        public virtual Raum StRaumNavigation { get; set; }
    }
}