// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SchulDbGenerator.Model
{
    [Table("Abteilung")]
    public partial class Abteilung
    {
        public Abteilung()
        {
            Klassens = new HashSet<Klasse>();
        }

        [Key]
        [Column("Abt_Nr")]
        [StringLength(3)]
        public string AbtNr { get; set; }
        [Column("Abt_Name")]
        [Required]
        [StringLength(255)]
        public string AbtName { get; set; }
        [Column("Abt_Leiter")]
        [StringLength(3)]
        public string AbtLeiter { get; set; }
        [ForeignKey(nameof(AbtLeiter))]
        [InverseProperty(nameof(Lehrer.Abteilungens))]
        public virtual Lehrer AbtLeiterNavigation { get; set; }
        [InverseProperty(nameof(Klasse.KAbteilungNavigation))]
        public virtual ICollection<Klasse> Klassens { get; set; }
    }
}