// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SchulDbGenerator.Model
{
    [Table("Gegenstand")]
    public partial class Gegenstand
    {
        public Gegenstand()
        {
            Pruefungens = new HashSet<Pruefung>();
            Stundens = new HashSet<Stunde>();
        }

        [Key]
        [Column("G_Nr")]
        [StringLength(8)]
        public string GNr { get; set; }
        [Required]
        [Column("G_Bez")]
        [StringLength(20)]
        public string GBez { get; set; }

        [InverseProperty(nameof(Pruefung.PGegenstandNavigation))]
        public virtual ICollection<Pruefung> Pruefungens { get; set; }
        [InverseProperty(nameof(Stunde.StGegenstandNavigation))]
        public virtual ICollection<Stunde> Stundens { get; set; }
    }
}